#ifndef __TSOCK_H
#define __TSOCK_H

#define HELLO 1

#ifdef _WIN32

#include <ws2tcpip.h>
#include <Winsock2.h>

#define EINTR WSAEINTR
#define EBADF WSAEBADF
#define EACCES WSAEACCES
#define EFAULT WSAEFAULT
#define EINVAL WSAEINVAL
#define EMFILE WSAEMFILE
#define EWOULDBLOCK WSAEWOULDBLOCK
#define EINPROGRESS WSAEINPROGRESS
#define EALREADY WSAEALREADY
#define ENOTSOCK WSAENOTSOCK
#define EDESTADDRREQ WSAEDESTADDRREQ
#define EMSGSIZE WSAEMSGSIZE
#define EPROTOTYPE WSAEPROTOTYPE
#define ENOPROTOOPT WSAENOPROTOOPT
#define EPROTONOSUPPORT WSAEPROTONOSUPPORT
#define ESOCKTNOSUPPORT WSAESOCKTNOSUPPORT
#define EOPNOTSUPP WSAEOPNOTSUPP
#define EPFNOSUPPORT WSAEPFNOSUPPORT
#define EAFNOSUPPORT WSAEAFNOSUPPORT
#define EADDRINUSE WSAEADDRINUSE
#define EADDRNOTAVAIL WSAEADDRNOTAVAIL
#define ENETDOWN WSAENETDOWN
#define ENETUNREACH WSAENETUNREACH
#define ENETRESET WSAENETRESET
#define ECONNABORTED WSAECONNABORTED
#define ECONNRESET WSAECONNRESET
#define ENOBUFS WSAENOBUFS
#define EISCONN WSAEISCONN
#define ENOTCONN WSAENOTCONN
#define ESHUTDOWN WSAESHUTDOWN
#define ETOOMANYREFS WSAETOOMANYREFS
#define ETIMEDOUT WSAETIMEDOUT
#define ECONNREFUSED WSAECONNREFUSED
#define ELOOP WSAELOOP
#define ENAMETOOLONG WSAENAMETOOLONG
#define EHOSTDOWN WSAEHOSTDOWN
#define EHOSTUNREACH WSAEHOSTUNREACH
#define ENOTEMPTY WSAENOTEMPTY
#define EPROCLIM WSAEPROCLIM
#define EUSERS WSAEUSERS
#define EDQUOT WSAEDQUOT
#define ESTALE WSAESTALE
#define EREMOTE WSAEREMOTE
#define SYSNOTREADY WSASYSNOTREADY
#define VERNOTSUPPORTED WSAVERNOTSUPPORTED
#define NOTINITIALISED WSANOTINITIALISED
#define EDISCON WSAEDISCON
#define ENOMORE WSAENOMORE
#define ECANCELLED WSAECANCELLED
#define EINVALIDPROCTABLE WSAEINVALIDPROCTABLE
#define EINVALIDPROVIDER WSAEINVALIDPROVIDER
#define EPROVIDERFAILEDINIT WSAEPROVIDERFAILEDINIT
#define SYSCALLFAILURE WSASYSCALLFAILURE
#define SERVICE_NOT_FOUND WSASERVICE_NOT_FOUND
#define TYPE_NOT_FOUND WSATYPE_NOT_FOUND
#define _E_NO_MORE WSA_E_NO_MORE
#define _E_CANCELLED WSA_E_CANCELLED
#define EREFUSED WSAEREFUSED
#define HOST_NOT_FOUND WSAHOST_NOT_FOUND
#define TRY_AGAIN WSATRY_AGAIN
#define NO_RECOVERY WSANO_RECOVERY
#define NO_DATA WSANO_DATA


#elif __linux__ 

#define FORLINUX 2

#include <netinet/in.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/wait.h>
#include <unistd.h>
#include <arpa/inet.h>

#endif

typedef struct sockaddr_in SA4;
typedef struct sockaddr SA;

#endif